/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package excel;

/**
 *
 * @author KAMINATOR
 */
public class ManualdeUsuario extends javax.swing.JFrame {

    /**
     * Creates new form ManualdeUsuario
     */
    public ManualdeUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel1.setText("<html><body><b> Manual de Usuario</b><br>" +
            "El siguiente manual le dará instrucciones de cómo se podrán usar la hoja de cálculo, las herramientas que se pueden utilizar que trae incluidas:\n<br><br>" +
            "<b>Escritura en la hoja de calculo</b>\n<br><br>" +
            "•	Para poder empezar a escribir en la hoja de calculo se le tiene que dar primero clic a una celda, entonces en ese momento tenemos dos, opciones 1 escribir desde la misma celda o bien escribir desde la barra de arriba.\n<br>" +
            "•	Al momento de borrar de mismo modo se puede borrar desde la barra y desde la misma celda.\n<br>" +
            "•	Para desplazarnos sobre la tabla se pueden usar las flechas o la opción de buscar una celda por medio de columna y fila\n<br><br>" +
            "<b>Herramientas:\n</b><br>" +
            "<b>Archivo\n</b><br>" +
            "•	Nuevo: Al dar click sobre esta opción, el programa le mostrará al usuario una ventana donde le dará dos opciones una si este quiere guardar los cambios que estaba haciendo en la hoja o bien descartarlos y simplemente comenzar una nueva.\n<br>" +
            "•	Abrir: Esta opción nos mostrara todos los archivos que han sido guardados y al elegir uno este nos mostrara en la hoja todos los datos guardados.\n<br>" +
            "•	Guardar: Esta mostrara una pestaña para indicarle el nombre con el que se quiere guardar el archivo, para luego guardar toda la información en ella.\n<br>" +
            "•	Eliminar: da la opción de eliminar uno de los archivos guardados\n<br>" +
            "•	Cerrar: Cierra completamente el programa\n<br><br>" +
            "<b>Letra</b>: La opción de letra nos mostrara 6 distintos tipos de letra de los cuales podemos elegir siendo estos los siguientes: Calibri, Palatino LinoType, Arial, Century, Comic Sans Ms. Tenga en cuenta que el tipo de letra afectara a toda la hoja y no a una celda por individual.\n<br>" +
            "<b>Alineado</b>: Esta opción nos permite alinear completamente una columna a la izquierda, derecha y centro. Para poder alinear se le debe dar click en una celda de la columna y luego dar la alineación o seleccionar cuantas celdas de la columna se quieren alinear. Para las letras ya escritas de una columna se debe de seleccionar y después alinear.\n<br>" +
            "<b>Tamaño de Letra</b>: En esta opción podemos elegir entre 3 tamaños de letra 12,15 y 20 que afectan a toda la tabla.\n<br>" +
            "<b>Cursiva (K)</b>: Esta aplica el estilo de letra cursiva para toda la tabla\n<br>" +
            "<b>Negrita (B)</b>: Esta aplica el estilo de negrito para toda la tabla\n<br>" +
            "<b>Subrayado (U)</b>: Esta subraya todo lo que hay en la tabla\n<br>" +
            "<b>Copiar</b>: Para esta opción tenemos que marcar una celda que tenga ya palabras escritas, luego darle click en esta opción.\n<br>" +
            "<b>Pegar</b>: Para la opción de pegar, ya una vez copiada una celda, centrarnos en una celda vacía para poder darle clic a esta opción. \n<br>" +
            "<b>Cortar</b>: En la siguiente opción al elegir una celda i al darle clic en esta opción quitara el texto y estará listo para pegar en otra celda\n<br><br>"+
            "<b>Número\n</b><br>" +
            "•	Fracción: Esta opción permite que los números enteros o decimales puedan ser convertidos a su equivalente en forma de fracción.\n<br>" +
            "•	Moneda: Esta permite que números enteros o decimales estén en formato de quetzales.\n<br>" +
            "•	General: Dependiendo si un numero esta en fracción, moneda o porcentaje, este lo ponga como solamente un número\n<br>" +
            "•	Porcentaje: Permite que un número se muestre en su forma equivalente de porcentaje\n<br><br>" +
            "<b>Ayuda\n</b><br>" +
            "•	En esta opción se encuentra el manual de usuario.\n<br><br>" +
            "<b>Operaciones\n</b><br>" +
            "•	Suma: Para esta opción el usuario tiene que marcar varias celdas donde cada una puede estar en formato distinto, donde le mostrara en la siguiente celda de abajo le tire el resultado de la suma\n<br>" +
            "•	Productoria: para esta opción de igual manera se tienen que seleccionar las celdas de una misma columna que contengan números para que así esta pueda operar y mostrar el resultado en la celda siguiente de la misma columna.\n<br>" +
            "•	Promedio: Esta opción saca el promedio de un numero de datos seleccionados de una misma columna.<br>"+
            "\n" +
            "</body></html>");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(398, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManualdeUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManualdeUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManualdeUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManualdeUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManualdeUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private volatile javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
